stages:
  build:
    nodeLabel: nvm
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install
        ENVIRONMENT=devint npm test
    filesToStash:
      - "**"
  prepublish:
    nodeLabel: nvm
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm i --no-save
        npm run build
        cp Dockerfile .dockerignore .webpack/service
    filesToStash:
      - ".webpack/"
  dockerPublish:
    dockerImages:
      - imageName: webhook-provisioner
        dockerfile: .webpack/service/Dockerfile
        context: .webpack/service
        buildArgs:
          VCS_REF: "{{GIT_COMMIT}}"
          VCS_URL: "{{GIT_URL}}"
          BUILD_DATE: "{{DATE}}"
          VERSION: "{{GIT_COMMIT}}"
        destinations:
          - registry: docker.dwolla.net/dwolla
            tags:
              - "{{GIT_COMMIT}}"
              - latest
  deployDevInt:
    nodeLabel: nvm-deployer
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm
        npm install -g serverless
        ENVIRONMENT=devint SKRIPTS_DEPLOYMENT_BUCKET=dwolla-encrypted npm run deploy
  deployUat:
    nodeLabel: nvm-deployer
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm
        npm install -g serverless
        ENVIRONMENT=uat SKRIPTS_DEPLOYMENT_BUCKET=dwolla-encrypted RETRIES_MAX=1 npm run deploy
  deployProd:
    nodeLabel: nvm-deployer
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm
        npm install -g serverless
        ENVIRONMENT=prod SKRIPTS_DEPLOYMENT_BUCKET=dwolla-encrypted npm run deploy

additionalJobs:
  - name: UpdateConsumerWebhookHandler
    nodeLabel: nvm-deployer
    parameters:
      - name: Environment
        type: Choice
        description: Dwolla environments
        choices:
          - devint
          - uat
          - prod
      - name: NodeVersion
        type: Choice
        description: supported node versions
        choices:
          - nodejs16.x
          - nodejs20.x
      - name: CodeName
        type: String
        description: Code name to use in handler. Found in s3 deployed code bucket for webhook handler.
      - name: ConsumerIds
        type: String
        description: Comma seperated list of consumer ids. Example '123, "app1", 456, "app2"'
    steps:
      - |
        aws lambda invoke \
        --region us-west-2 \
        --function-name webhook-provisioner-${Environment}-updateConsumersCode \
        --payload '{"consumerIds":[$ConsumerIds],"nodeVersion":"$NodeVersion","codeName":"$CodeName"}' \
        --output json out.json
